version: 2
jobs:
  build:
    docker: # requires
      - image: circleci/node:7.10
    branches:
      only:
        - $PRODUCTION_BRANCH
    steps:
      - checkout
      - run:
          name: pre setup
          command: |
            sudo pip install awscli
      - run:
          name: deployment
          command: |
            aws s3 rm s3://$BUCKET_NAME/* --recursive
            aws s3 cp docs/ s3://$BUCKET_NAME/ --recursive