version: 2
jobs:
  build:
    working_directory: ~/repo
    docker: # requires
      - image: circleci/node:7.10
    branches:
      only:
        - master
    steps:
      - checkout
      - run:
          name: show environments
          command: |
            cat /etc/issue
      - run:
          name: Install dependencies
          working_directory: ./
          command: |
            sudo apt-get -y -qq update
            sudo apt-get -y -qq install python3.4-dev
            sudo curl -O https://bootstrap.pypa.io/get-pip.py
            sudo python3.4 get-pip.py
            sudo pip install awscli --upgrade
      - run:
          name: Setup env file
          command: |
            echo "GOOGLE_MAP_API_KEY=$GOOGLE_MAP_API_KEY\n" \
                 "GOOGLE_ANALYTICS_ID=$GOOGLE_ANALYTICS_ID" > .env
      - restore_cache:
          name: Restoring Cache node_modules
          keys:
            - node-{{ checksum "package.json" }}
            - node-
      - run:
          name: Setup npm
          command: |
            npm install
            sudo npm install -g gulp
            npm rebuild node-sass --force
      - save_cache:
          name: Saving Cache node_modules
          key: node-{{ checksum "package.json" }}
          paths:
            - "./node_modules"
      - run:
          name: Build project
          command: |
            gulp
      - run:
          name: Unit test
          command: |
            npm run test
      - run:
          name: Deployment
          command: |
            aws s3 rm s3://$BUCKET_NAME/* --recursive
            aws s3 cp docs/ s3://$BUCKET_NAME/ --recursive
